services:
  books-db:
    container_name: books-db
    image: ghcr.io/linuxserver/mariadb:11.4.9@sha256:05cefe72b4d07d35cf0c4229b44020a7afdd43e0f152968a44431f84ca3eeb4f
    labels:
      folder.view3: Media
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/mariadb.png
    volumes:
      - "${SECRET_APPDATA}/grimmory/db:/config"
    environment:
      TZ: ${TZ}
      PUID: ${UID}
      GUID: ${GID}
      MYSQL_ROOT_PASSWORD: ${GRIMMORY_MARIADB_ROOTPW}
      MYSQL_DATABASE: ${GRIMMORY_DB}
      MYSQL_USER: ${GRIMMORY_MARIADB_USERNAME}
      MYSQL_PASSWORD: ${GRIMMORY_MARIADB_PASSWORD}
    networks:
      - media-backend
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
