services:
  books-db:
    container_name: books-db
    image: ghcr.io/linuxserver/mariadb:11.4.10@sha256:c317e6d00c8b5403a655728c0dd4f93a93f17dff468c48713a28641dda46fed6
    labels:
      folder.view3: Media
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/mariadb.png
    volumes:
      - "${SECRET_APPDATA}/grimmory/db:/config"
    environment:
      TZ: ${TZ}
      PUID: ${UID}
      PGID: ${GID}
      MYSQL_ROOT_PASSWORD: ${GRIMMORY_MARIADB_ROOTPW}
      MYSQL_DATABASE: ${GRIMMORY_DB}
      MYSQL_USER: ${GRIMMORY_MARIADB_USERNAME}
      MYSQL_PASSWORD: ${GRIMMORY_MARIADB_PASSWORD}
    networks:
      - media-backend
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
