services:
  books-db:
    container_name: books-db
    image: ghcr.io/linuxserver/mariadb:11.4.11@sha256:2d06ae7bc1c259e0762c654f2619db0eb93925d11a6d38041f24f3bcb16408e8
    labels:
      folder.view3: Media
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/mariadb.png
    volumes:
      - "${SECRET_APPDATA}/grimmory/db:/config"
    environment:
      TZ: ${TZ}
      PUID: ${UID}
      PGID: ${GID}
      MYSQL_ROOT_PASSWORD: ${GRIMMORY_MARIADB_ROOTPW}
      MYSQL_DATABASE: ${GRIMMORY_DB}
      MYSQL_USER: ${GRIMMORY_MARIADB_USERNAME}
      MYSQL_PASSWORD: ${GRIMMORY_MARIADB_PASSWORD}
    networks:
      - media-backend
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
