services:
  immich-redis:
    container_name: immich_redis
    image: ghcr.io/valkey-io/valkey:9@sha256:64e361b630ecf18dff7ca4df6a88e6eafc193687eb48cff2c7e0a293ab67d29a
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
    labels:
      folder.view3: Immich
      net.unraid.docker.icon: file://${SECRET_APPDATA}/icons/redis.png
    networks:
      - immich-db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SECRET_APPDATA}/immich/redis:/data
    environment:
      TZ: ${TZ}
    restart: always
    healthcheck:
      test: redis-cli ping || exit 1
