services:
  immich-redis:
    container_name: immich_redis
    image: ghcr.io/valkey-io/valkey:9@sha256:418652cfb58ef879d4978c33553735d7147016032d5aefaa14c828e611eb9dfd
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
    labels:
      folder.view3: Immich
      net.unraid.docker.icon: file://${SECRET_APPDATA}/icons/redis.png
    networks:
      - immich-db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SECRET_APPDATA}/immich/redis:/data
    environment:
      TZ: ${TZ}
    restart: always
    healthcheck:
      test: redis-cli ping | grep -q PONG || exit 1
