services:
  immich-redis:
    container_name: immich_redis
    image: ghcr.io/valkey-io/valkey:8@sha256:1f84517eca8e0dd9585ed57c572796f32839e1b0e7ce07ad28e6bce098468371
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
    labels:
      folder.view3: Immich
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/redis.png
    networks:
      - immich-db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SECRET_APPDATA}/immich/redis:/data
    environment:
      TZ: ${TZ}
    restart: always
    healthcheck:
      test: redis-cli ping || exit 1
