services:
  clonarr:
    container_name: clonarr
    image: ghcr.io/prophetse7en/clonarr:v2.5.6@sha256:8cfc257d94f018f25a03eadf5d3aae9f1a4470f3cb25e0cf00eb0d60f532c67d
    labels:
      folder.view3: Media
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/clonarr.png
      traefik.enable: true
      traefik.docker.network: homelab_media
      traefik.http.routers.clonarr.rule: Host(`clonarr.${SECRET_DOMAIN}`)
      traefik.http.routers.clonarr.entryPoints: websecure
      traefik.http.services.clonarr.loadbalancer.server.port: 6060
    environment:
      TZ: ${TZ}
      PUID: ${UID}
      PGID: ${GID}
    volumes:
      - "${SECRET_APPDATA}/clonarr:/config"
    restart: unless-stopped
    networks:
      - media
