services:
  clonarr:
    container_name: clonarr
    image: ghcr.io/prophetse7en/clonarr:v2.2.6@sha256:cfa6cfe63912d4b864f8257ee6eb16c281d010bbc3175e690fa00132a04a6944
    labels:
      folder.view3: Media
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/clonarr.png
      traefik.enable: true
      traefik.docker.network: homelab_media
      traefik.http.routers.clonarr.rule: Host(`clonarr.${SECRET_DOMAIN}`)
      traefik.http.routers.clonarr.entryPoints: websecure
      traefik.http.services.clonarr.loadbalancer.server.port: 6060
    environment:
      TZ: ${TZ}
      PUID: ${UID}
      PGID: ${GID}
    volumes:
      - "${SECRET_APPDATA}/clonarr:/config"
    restart: unless-stopped
    networks:
      - media
