services:
  clonarr:
    container_name: clonarr
    image: ghcr.io/prophetse7en/clonarr:v2.5.3@sha256:35c1c7f8e94470f3ab0bd9af3d3d9b4fc0a4828459d868718540c20d89e2725c
    labels:
      folder.view3: Media
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/clonarr.png
      traefik.enable: true
      traefik.docker.network: homelab_media
      traefik.http.routers.clonarr.rule: Host(`clonarr.${SECRET_DOMAIN}`)
      traefik.http.routers.clonarr.entryPoints: websecure
      traefik.http.services.clonarr.loadbalancer.server.port: 6060
    environment:
      TZ: ${TZ}
      PUID: ${UID}
      PGID: ${GID}
    volumes:
      - "${SECRET_APPDATA}/clonarr:/config"
    restart: unless-stopped
    networks:
      - media
