services:
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/linuxserver/jellyfin:10.11.8@sha256:ae1ac3d89b8598f31f5e1dc5aff898e13eab617303db58f84956e26f7b78c198
    labels:
      folder.view3: Media
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/jellyfin.png
      traefik.enable: true
      traefik.docker.network: homelab_media
      traefik.http.routers.jellyfin.rule: Host(`vod.${SECRET_DOMAIN}`)
      traefik.http.routers.jellyfin.entryPoints: websecure
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096
      traefik.http.services.jellyfin.loadbalancer.server.scheme: http
    volumes:
      - "${SECRET_APPDATA}/jellyfin:/config"
      - "${SECRET_DATADIR}/media:/media"
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    environment:
      TZ: ${TZ}
      PUID: ${UID}
      PGID: ${GID}
      #JELLYFIN_PublishedServerUrl: http://vod.${SECRET_HOME_DOMAIN} # Unused unless Macvlan
      DOCKER_MODS: linuxserver/mods:jellyfin-amd
    networks:
      media:
    restart: always
