services:
  komga:
    container_name: komga
    image: ghcr.io/gotson/komga:1.26.1@sha256:e109902ebebb8a05f633f48d84a2ac7bb1334bf0f6fbc17262a333082c7de44d
    labels:
      folder.view3: Media
      net.unraid.docker.icon: file://${SECRET_APPDATA}/icons/komga.png
      traefik.enable: true
      traefik.docker.network: homelab_media
      traefik.http.routers.komga.rule: Host(`comics.${SECRET_DOMAIN}`)
      traefik.http.routers.komga.entryPoints: websecure
      traefik.http.services.komga.loadbalancer.server.port: 25600
    user: "1000:1000"
    volumes:
      - "${SECRET_APPDATA}/komga/config:/config"
      - "${SECRET_DATADIR}/media/bd-manga-comics:/bd-manga-comics"
    environment:
      TZ: ${TZ}
    networks:
      - media
    restart: always
