services:
  komga:
    container_name: komga
    image: ghcr.io/gotson/komga:1.26.2@sha256:8bc00f642c82a7b5148c2c49289cd5f2289402072f2c9d83ccfecde5d5e55e5f
    labels:
      folder.view3: Media
      net.unraid.docker.icon: file://${SECRET_APPDATA}/icons/komga.png
      traefik.enable: true
      traefik.docker.network: homelab_media
      traefik.http.routers.komga.rule: Host(`comics.${SECRET_DOMAIN}`)
      traefik.http.routers.komga.entryPoints: websecure
      traefik.http.services.komga.loadbalancer.server.port: 25600
    user: "1000:1000"
    volumes:
      - "${SECRET_APPDATA}/komga/config:/config"
      - "${SECRET_DATADIR}/media/bd-manga-comics:/bd-manga-comics"
    environment:
      TZ: ${TZ}
    networks:
      - media
    restart: always
