services:
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/home-operations/prowlarr:2.6.5@sha256:6152751c3ea2e7751564f5952173d5e83eed0e09f3fabd2cb6bdb58690c39e2f
    labels:
      folder.view3: Media
      net.unraid.docker.icon: file://${SECRET_APPDATA}/icons/prowlarr.png
      traefik.enable: true
      traefik.docker.network: homelab_media
      traefik.http.routers.prowlarr.rule: Host(`indexer.${SECRET_DOMAIN}`)
      traefik.http.routers.prowlarr.entryPoints: websecure
      traefik.http.services.prowlarr.loadbalancer.server.port: 9696
    volumes:
      - "${SECRET_APPDATA}/prowlarr:/config"
    user: ${UID}:${GID}
    environment:
      TZ: ${TZ}
      COMPlus_EnableDiagnostics: "0" # Fix the .Net CoreCLR crash on ReadOnly Filesystem
      PROWLARR__ANALYTICS_ENABLED: false
      PROWLARR__THEME: dark
    networks:
      - media
      - media-backend
      - gluetun
    restart: always
