services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/linuxserver/qbittorrent:5.1.4@sha256:6a7ffbfff04dd109bff37c474bfee00aa08dea5edb78c670439be3ed242b70fa
    labels:
      folder.view2: Media
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/qbittorrent.png
    volumes:
      - "${SECRET_APPDATA}/qbittorrent:/config"
      - "${SECRET_DATADIR}/downloads:/data/downloads"
    user: ${UID}:${GID}
    environment:
      PUID:
      PGID:
      TZ: ${TZ}
      WEBUI_PORT: 8080
      TORRENTING_PORT: ${VPN_FORWARDED_PORT}
    network_mode: service:gluetun
    restart: always
