services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/linuxserver/qbittorrent:5.1.1@sha256:1afa9ee70f38adaebb4b2ade4e720d9add5b7d4f0ef4e679f17d94ca002f00bc
    labels:
      folder.view: Media
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/qbittorrent.png
    volumes:
      - "${SECRET_APPDATA}/qbittorrent:/config"
      - "${SECRET_DATADIR}/downloads:/data/downloads"
    user: ${UID}:${GID}
    environment:
      PUID:
      PGID:
      TZ: ${TZ}
      WEBUI_PORT: 8080
      TORRENTING_PORT: ${VPN_FORWARDED_PORT}
    network_mode: service:gluetun
    restart: always
