services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/linuxserver/qbittorrent:5.1.4@sha256:1fc78c81850d658f17701bfa9d8de58ccc12ff27d36a9a176c6299e55aaf4b4e
    labels:
      folder.view3: Media
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/qbittorrent.png
    volumes:
      - "${SECRET_APPDATA}/qbittorrent:/config"
      - "${SECRET_DATADIR}/downloads:/data/downloads"
    user: ${UID}:${GID}
    environment:
      PUID:
      PGID:
      TZ: ${TZ}
      WEBUI_PORT: 8080
      TORRENTING_PORT: ${VPN_FORWARDED_PORT}
    network_mode: service:gluetun
    restart: always
