services:
  sonarr:
    container_name: sonarr
    image: ghcr.io/home-operations/sonarr:4.0.19@sha256:f3f87b789aca4e27eb60401e0782200b351b727d3b55d42279dbfb4b24f00d9c
    labels:
      folder.view3: Media
      net.unraid.docker.icon: file://${SECRET_APPDATA}/icons/sonarr.png
      traefik.enable: true
      traefik.docker.network: homelab_media
      traefik.http.routers.sonarr.rule: Host(`sonarr.${SECRET_DOMAIN}`)
      traefik.http.routers.sonarr.entryPoints: websecure
      traefik.http.services.sonarr.loadbalancer.server.port: 8989
    volumes:
      - "${SECRET_APPDATA}/sonarr:/config"
      - "${SECRET_DATADIR}:/data"
    user: ${UID}:${GID}
    environment:
      TZ: ${TZ}
      COMPlus_EnableDiagnostics: "0" # Fix the .Net CoreCLR crash on ReadOnly Filesystem
    networks:
      - media
      - media-backend
      - gluetun
    restart: always
