services:
  sonarr:
    container_name: sonarr
    image: ghcr.io/home-operations/sonarr:4.0.17@sha256:83607d2b741ec9469db09489e88c473ae6fdf7d85f3b55d4fa809b43e25a2a6c
    labels:
      folder.view3: Media
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/sonarr.png
      traefik.enable: true
      traefik.docker.network: homelab_media
      traefik.http.routers.sonarr.rule: Host(`sonarr.${SECRET_DOMAIN}`)
      traefik.http.routers.sonarr.entryPoints: websecure
      traefik.http.services.sonarr.loadbalancer.server.port: 8989
    volumes:
      - "${SECRET_APPDATA}/sonarr:/config"
      - "${SECRET_DATADIR}:/data"
    user: ${UID}:${GID}
    environment:
      TZ: ${TZ}
      COMPlus_EnableDiagnostics: "0" # Fix the .Net CoreCLR crash on ReadOnly Filesystem
    networks:
      - media
      - media-backend
      - gluetun
    restart: always
