services:
  traefik-socket:
    container_name: traefik-socket
    image: ghcr.io/wollomatic/socket-proxy:1.13.0@sha256:be7a61fc50baf0add95d94442c3d40cddc4594925a564f22ba870eb017ceae9f
    labels:
      folder.view3: Ingress
      net.unraid.docker.icon: file://${SECRET_APPDATA}/icons/docker-socket.png
    user: 65534:281
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    command:
      - "-loglevel=debug"
      - "-shutdowngracetime=5"
      - "-watchdoginterval=600"
      - "-stoponwatchdog"
      - "-allowfrom=traefik"
      - "-listenip=0.0.0.0"
      - '-allowGET=/v1\..{1,2}/(version|containers/.*|events.*)'
      - "-allowHEAD=/_ping"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-socket
    restart: always
