services:
  traefik-socket:
    container_name: traefik-socket
    image: ghcr.io/wollomatic/socket-proxy:1.12.2@sha256:bc08381bae4c2a2050f774f15d63629caf3d884c5f02fa57ff5f76a960b2ccb8
    labels:
      folder.view3: Ingress
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/docker-socket.png
    user: 65534:281
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    command:
      - "-loglevel=debug"
      - "-shutdowngracetime=5"
      - "-watchdoginterval=600"
      - "-stoponwatchdog"
      - "-allowfrom=traefik"
      - "-listenip=0.0.0.0"
      - '-allowGET=/v1\..{1,2}/(version|containers/.*|events.*)'
      - "-allowHEAD=/_ping"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-socket
    restart: always
