services:
  traefik-socket:
    container_name: traefik-socket
    image: ghcr.io/wollomatic/socket-proxy:1.11.3@sha256:6da20bdfa69144b203ebf82ee3e1f35d434bcf49a609349e90973d193c7de8f6
    labels:
      folder.view2: Ingress
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/docker-socket.png
    user: 65534:281
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    command:
      - '-loglevel=debug'
      - '-shutdowngracetime=5'
      - '-watchdoginterval=600'
      - '-stoponwatchdog'
      - '-allowfrom=traefik'
      - '-listenip=0.0.0.0'
      - '-allowGET=/v1\..{1,2}/(version|containers/.*|events.*)'
      - '-allowHEAD=/_ping'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-socket
    restart: always
