services:
  hassio-esphome:
    container_name: hassio-esphome
    image: ghcr.io/esphome/esphome:2026.6.2@sha256:526a75c8d64a0d962a3b088c3af4fa7cf8ecf7161b995be57fc95b0726496a39
    labels:
      folder.view3: Hassio
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/esphome.png
    volumes:
      - "${SECRET_APPDATA}/hassio/esphome:/config"
    environment:
      TZ: ${TZ}
    networks:
      - hassio-net
    restart: always
