services:
  hassio-esphome:
    container_name: hassio-esphome
    image: ghcr.io/esphome/esphome:2026.7.0@sha256:959ef36e5ea97c8309429f0ba1405ddb2eead19019b81e6e9518e683dff5191c
    labels:
      folder.view3: Hassio
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/esphome.png
    volumes:
      - "${SECRET_APPDATA}/hassio/esphome:/config"
    environment:
      TZ: ${TZ}
    networks:
      - hassio-net
    restart: always
