services:
  hassio-esphome:
    container_name: hassio-esphome
    image: ghcr.io/esphome/esphome:2026.9.1@sha256:776a845d508909bf426d2ee7bdd81796361ebe6a7f091807ce1d6d0b48985413
    labels:
      folder.view3: Hassio
      net.unraid.docker.icon: file://${SECRET_APPDATA}/icons/esphome.png
    volumes:
      - "${SECRET_APPDATA}/hassio/esphome:/config"
    environment:
      TZ: ${TZ}
    networks:
      - hassio-net
    restart: always
