services:
  hassio-mqtt:
    container_name: hassio-mqtt
    image: docker.io/eclipse-mosquitto:2.1.2-alpine@sha256:38c0da4f2ef84284d47b3b3eeea1cb3bdeabe81ee10caf0cd5c5ff61ee3ea408
    labels:
      folder.view3: Hassio
      net.unraid.docker.icon: file://${SECRET_APPDATA}/icons/mqtt.png
    ports:
      - "8883:8883"
    volumes:
      - "${SECRET_APPDATA}/hassio/mqtt/config/:/mosquitto/config"
      - "${SECRET_APPDATA}/hassio/mqtt/data/:/mosquitto/data/"
    user: ${UID}:${GID}
    environment:
      TZ: ${TZ}
    networks:
      - hassio-net
      - hassio-frigate
    restart: always
