services:
  hassio-mqtt:
    container_name: hassio-mqtt
    image: docker.io/eclipse-mosquitto:2.1.2-alpine@sha256:a908c65cc8e67ec9d292ef27c2c0360dbaaee7eb1b935cdd194e67697f15dea1
    labels:
      folder.view3: Hassio
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/mqtt.png
    ports:
      - "8883:8883"
    volumes:
      - "${SECRET_APPDATA}/hassio/mqtt/config/:/mosquitto/config"
      - "${SECRET_APPDATA}/hassio/mqtt/data/:/mosquitto/data/"
    user: ${UID}:${GID}
    environment:
      TZ: ${TZ}
    networks:
      - hassio-net
      - hassio-frigate
    restart: always
