services:
  hassio-mqtt:
    container_name: hassio-mqtt
    image: docker.io/eclipse-mosquitto:2.1.2-alpine@sha256:6f8d8a947c506f8a2290ec65cd4bd2bc7cb4d43fb5f6271f861cb013e2ef9797
    labels:
      folder.view3: Hassio
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/mqtt.png
    ports:
      - "8883:8883"
    volumes:
      - "${SECRET_APPDATA}/hassio/mqtt/config/:/mosquitto/config"
      - "${SECRET_APPDATA}/hassio/mqtt/data/:/mosquitto/data/"
    user: ${UID}:${GID}
    environment:
      TZ: ${TZ}
    networks:
      - hassio-net
      - hassio-frigate
    restart: always
