services:
  hassio-server:
    container_name: hassio-server
    image: homeassistant/home-assistant:2026.4.1@sha256:8848691147f01a6eee7753de2ade21b04d6168fcd2e2a7089f6f84e3b7b86960
    labels:
      folder.view3: Hassio
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/hassio.png
      net.unraid.docker.link: hassio.${SECRET_DOMAIN}
      traefik.enable: true
      traefik.docker.network: homelab_hassio-front
      traefik.http.routers.hassio-server.rule: Host(`hassio.${SECRET_DOMAIN}`)
      traefik.http.routers.hassio-server.entryPoints: websecure
      traefik.http.services.hassio-server.loadbalancer.server.port: 8123
    volumes:
      - "${SECRET_APPDATA}/hassio/config:/config"
      - "${SECRET_APPDATA}/hassio/media:/media"
    environment:
      TZ: ${TZ}
    networks:
      lan:
        ipv4_address: 192.168.1.11
      hassio-front:
      hassio-net:
      hassio-frigate:
    restart: unless-stopped
