services:
  hassio-server:
    container_name: hassio-server
    image: homeassistant/home-assistant:2026.8.2@sha256:56690a89c79a0de98035e1719f8324a92d5859c1192ff45adb0230ea81cb42a5
    labels:
      folder.view3: Hassio
      net.unraid.docker.icon: file://${SECRET_APPDATA}/icons/hassio.png
      net.unraid.docker.link: hassio.${SECRET_DOMAIN}
      traefik.enable: true
      traefik.docker.network: homelab_hassio-front
      traefik.http.routers.hassio-server.rule: Host(`hassio.${SECRET_DOMAIN}`)
      traefik.http.routers.hassio-server.entryPoints: websecure
      traefik.http.services.hassio-server.loadbalancer.server.port: 8123
    volumes:
      - "${SECRET_APPDATA}/hassio/config:/config"
      - "${SECRET_APPDATA}/hassio/media:/media"
    environment:
      TZ: ${TZ}
    networks:
      lan:
        ipv4_address: 192.168.1.11
      hassio-front:
      hassio-net:
      hassio-frigate:
    restart: unless-stopped
