services:
  hassio-somfyprotect2mqtt:
    container_name: hassio-somfyprotect2mqtt
    image: docker.io/minims/somfyprotect2mqtt:2026.3.0@sha256:0dd1655ef08dce2bbc7caaf4b32d7a0350ee70481ac3c5a58c161db3cfb5a716
    labels:
      folder.view2: Hassio
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/somfyprotect.png
    volumes:
      - "${SECRET_APPDATA}/hassio/somfyprotect2mqtt:/config"
    environment:
      TZ: ${TZ}
    networks:
      - hassio-net
    restart: always
