services:
  hassio-somfyprotect2mqtt:
    container_name: hassio-somfyprotect2mqtt
    image: docker.io/minims/somfyprotect2mqtt:2026.8.3@sha256:2ff09df7b92b26091743c74ffb07fd583108376dd397919a1410d2fcd9c80189
    labels:
      folder.view3: Hassio
      net.unraid.docker.icon: file://${SECRET_APPDATA}/icons/somfyprotect.png
    volumes:
      - "${SECRET_APPDATA}/hassio/somfyprotect2mqtt:/config"
    environment:
      TZ: ${TZ}
    networks:
      - hassio-net
    restart: always
