version: "3"
services:
  adguard:
    hostname: adguard
    domainname: home.lan
    image: adguard/adguardhome:v0.107.73@sha256:7fbf01d73ecb7a32d2d9e6cef8bf88e64bd787889ca80a1e8bce30cd4c084442
    network_mode: "host"
    environment:
      TZ: 'Europe/Paris'
    # Volumes store your data between container upgrades
    volumes:
      - 'conf:/opt/adguardhome/conf'
      - 'work:/opt/adguardhome/work'
    restart: unless-stopped

volumes:
  conf:
  work:
