version: "3"
services:
  dns:
    hostname: dns
    domainname: home.lan
    image: docker.io/technitium/dns-server:15.6.0@sha256:1045db38fd2f2e4d9578f9168b7eb4862575469ed0ffc79e03f36bdc772a93b5
    network_mode: "host"
    environment:
      TZ: 'Europe/Paris'
      DNS_SERVER_DOMAIN: "home.lan"
    volumes:
      - 'config:/etc/dns'
      - 'log:/var/log/technitium/dns'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:5380/api/dnsClient/healthCheck | grep '\"status\":\"ok\"'"]
      #test: ["CMD", "dig", "+short", "+norecurse", "+retry=0", "@127.0.0.1", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  config:
  log:
