version: "3"
services:
  dns:
    hostname: dns
    domainname: home.lan
    image: docker.io/technitium/dns-server:15.5.0@sha256:2502fd4993d18a8c6665ce6eefb20c76ca21918c5435a015d9485b36e8275b5e
    network_mode: "host"
    environment:
      TZ: 'Europe/Paris'
      DNS_SERVER_DOMAIN: "home.lan"
    volumes:
      - 'config:/etc/dns'
      - 'log:/var/log/technitium/dns'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:5380/api/dnsClient/healthCheck | grep '\"status\":\"ok\"'"]
      #test: ["CMD", "dig", "+short", "+norecurse", "+retry=0", "@127.0.0.1", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  config:
  log:
