version: "3"
services:
  dns:
    hostname: dns
    domainname: home.lan
    image: docker.io/technitium/dns-server:15.3.0@sha256:c5ea91d9018688ef7e671fbbba2b7c0ff6434b0cc18b4edfa6a68142b39984eb
    network_mode: "host"
    environment:
      TZ: 'Europe/Paris'
      DNS_SERVER_DOMAIN: "home.lan"
    volumes:
      - 'config:/etc/dns'
      - 'log:/var/log/technitium/dns'
    restart: unless-stopped

volumes:
  config:
  log:
