services:
  authelia:
    container_name: authelia
    image: ghcr.io/authelia/authelia:4.39.24@sha256:8f428b06bb07bb978c10477527634f19ef3b049c9c87321fda14e24d8fc4c535
    labels:
      folder.view3: Security
      net.unraid.docker.icon: file://${SECRET_APPDATA}/icons/authelia.png
      traefik.enable: true
      traefik.docker.network: homelab_authelia
      traefik.http.routers.authelia.rule: Host(`login.${SECRET_DOMAIN}`)
      traefik.http.routers.authelia.entryPoints: websecure
      traefik.http.services.authelia.loadbalancer.server.port: 9091
    volumes:
      - "${SECRET_APPDATA}/authelia/config:/config"
    environment:
      TZ: ${TZ}
    networks:
      - authelia
      - lldap-internal
      - authelia-db
    restart: always
