services:
  authelia:
    container_name: authelia
    image: ghcr.io/authelia/authelia:4.39.18@sha256:ac379ba7680cea6ea21a29b65bf6daabb5aec5b4412c5591ec71df4fd156c789
    labels:
      folder.view3: Security
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/authelia.png
      traefik.enable: true
      traefik.docker.network: homelab_authelia
      traefik.http.routers.authelia.rule: Host(`login.${SECRET_DOMAIN}`)
      traefik.http.routers.authelia.entryPoints: websecure
      traefik.http.services.authelia.loadbalancer.server.port: 9091
    volumes:
      - "${SECRET_APPDATA}/authelia/config:/config"
    environment:
      TZ: ${TZ}
    networks:
      - authelia
      - lldap-internal
      - authelia-db
    restart: always
