services:
  authelia:
    container_name: authelia
    image: ghcr.io/authelia/authelia:4.39.26@sha256:16b804fbf6704b456ffb6e474c8e9d2406f9544ca0fecfeca7b4dcbed647deb4
    labels:
      folder.view3: Security
      net.unraid.docker.icon: file://${SECRET_APPDATA}/icons/authelia.png
      traefik.enable: true
      traefik.docker.network: homelab_authelia
      traefik.http.routers.authelia.rule: Host(`login.${SECRET_DOMAIN}`)
      traefik.http.routers.authelia.entryPoints: websecure
      traefik.http.services.authelia.loadbalancer.server.port: 9091
    volumes:
      - "${SECRET_APPDATA}/authelia/config:/config"
    environment:
      TZ: ${TZ}
    networks:
      - authelia
      - lldap-internal
      - authelia-db
    restart: always
