services:
  authelia-redis:
    container_name: authelia-redis
    image: docker.io/redis:8.6@sha256:d4a4a4db02748731e6313d60adfd92985b6ad7bc2f2400a6cb0f8b35a2a6b492
    labels:
      folder.view3: Security
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/redis.png
    volumes:
      - "${SECRET_APPDATA}/authelia/redis:/bitnami/redis/"
    networks:
      - authelia-db
    environment:
      TZ: ${TZ}
      REDIS_PASSWORD: ${SECRET_AUTHELIA_REDIS_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
