services:
  authelia-redis:
    container_name: authelia-redis
    image: docker.io/redis:8.6@sha256:009cc37796fbdbe1b631b4cc0582bed167e5e403ed8bcd06f77eb6cb5aeb6f93
    labels:
      folder.view2: Security
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/redis.png
    volumes:
      - "${SECRET_APPDATA}/authelia/redis:/bitnami/redis/"
    networks:
      - authelia-db
    environment:
      TZ: ${TZ}
      REDIS_PASSWORD: ${SECRET_AUTHELIA_REDIS_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
