services:
  authelia-redis:
    container_name: authelia-redis
    image: docker.io/redis:8.10@sha256:a7efd4ed5037dcfe1543c0e50b9f06293d3e88827005544bf37f381eea5f01cf
    command: redis-server --requirepass "${SECRET_AUTHELIA_REDIS_PASSWORD}"
    labels:
      folder.view3: Security
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/redis.png
    volumes:
      - "${SECRET_APPDATA}/authelia/redis:/data"
    networks:
      - authelia-db
    environment:
      TZ: ${TZ}
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
