services:
  backrest:
    container_name: backrest
    hostname: unraid-backrest
    image: ghcr.io/garethgeorge/backrest:v1.14.1@sha256:b852979754281026230cc69fb11428e6d57c9a97784ab4a444ffc7934c53a215
    labels:
      folder.view3: Tools
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/backrest.png
    ports:
      - "192.168.1.12:9898:9898"
    volumes:
      # Backrest app folders
      - ${SECRET_APPDATA}/backrest/data:/data
      - ${SECRET_APPDATA}/backrest/config:/config
      - ${SECRET_APPDATA}/backrest/cache:/cache
      # Backrest Unraid backup folders
      - /mnt:/mnt:rw,rslave
    environment:
      TZ: ${TZ}
      BACKREST_DATA: /data
      BACKREST_CONFIG: /config/config.json
      XDG_CACHE_HOME: /cache
    networks:
      - backrest
    restart: always

networks:
  backrest:
