services:
  db-backup:
    container_name: db-backup
    image: ghcr.io/tiredofit/docker-db-backup:4.1.99@sha256:d547726ad13079fb1441b1d21f85f043a634cfeda1e013101ca8ba1fc3cf838e
    labels:
      folder.view2: Tools
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/db-backup.png
    volumes:
      # Default Volumes
      - ${SECRET_APPDATA}/db-backup/scripts:/assets/scripts
      - ${SECRET_BACKUPSHARE}/databases:/backup
    environment:
      TIMEZONE: ${TZ}
      CONTAINER_ENABLE_MONITORING: false
      #DEBUG_MODE=TRUE
      USER_DBBACKUP: ${UID}
      GROUP_DBBACKUP: ${GID}
      BACKUP_JOB_CONCURRENCY: 3
      DEFAULT_BACKUP_BEGIN: "00 00 * * *" # Default backup everyday at midnight
      DEFAULT_CLEANUP_TIME: 8640 # Cleanup backups after a week
      DEFAULT_BACKUP_LOCATION: FILESYSTEM
      DEFAULT_FILESYSTEM_PATH: /backup
      DEFAULT_COMPRESSION: GZ
      DEFAULT_GZ_RSYNCABLE: true
      DEFAULT_MYSQL_CLIENT: mariadb
      ### Booklore DB
      DB01_TYPE: mysql
      DB01_HOST: books-db
      DB01_NAME: ALL
      DB01_USER: ${GRIMMORY_MARIADB_USERNAME}
      DB01_PASS: ${GRIMMORY_MARIADB_PASSWORD}
      DB01_BACKUP_BEGIN: "45 01 * * *" # https://crontab.guru/#45_01_*_*_*
      DB01_CLEANUP_TIME: 43200 # 1 Mois
    networks:
      - media-backend
    restart: always
