services:
  grafana:
    container_name: grafana
    image: docker.io/grafana/grafana:12.3.5@sha256:a604f143dbb145a16cd58d22b1451826ee59fcf9de561dc6d698b1de222272d0
    labels:
      folder.view2: Tools
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/grafana.png
      traefik.enable: true
      traefik.docker.network: homelab_tools
      traefik.http.routers.grafana.rule: Host(`graph.${SECRET_DOMAIN}`)
      traefik.http.routers.grafana.entryPoints: websecure
      traefik.http.services.grafana.loadbalancer.server.port: 3000
    volumes:
      - "${SECRET_APPDATA}/grafana/data:/var/lib/grafana"
      - "${SECRET_APPDATA}/grafana/provisionning:/etc/grafana/provisioning"
    user: ${UID}:${GID}
    environment:
      TZ: ${TZ}
      GF_DEFAULT_INSTANCE_NAME: "Cosmicvault Graphs"
      GF_SERVER_PROTOCOL: "http"
      GF_SERVER_ENABLE_GZIP: true
      GF_DATABASE_TYPE: "sqlite3"
      GF_REMOTE_CACHE_TYPE: "memcached"
      GF_REMOTE_CACHE_CONNSTR: "127.0.0.1:11211"
      GF_ANALYTICS_ENABLED: false
      GF_ANALYTICS_REPORTING_ENABLED: false
      GF_ANALYTICS_CHECK_FOR_UPDATES: false
      GF_USERS_ALLOW_SIGN_UP: false
      GF_USERS_ALLOW_ORG_CREATE: false
      GF_USERS_VERIFY_EMAIL_ENABLED: false
      GF_AUTH_ANONYMOUS_ENABLED: false
    networks:
      - tools
      - hassio-net
    restart: always
