services:
  homebox:
    container_name: homebox
    image: ghcr.io/sysadminsmedia/homebox:0.26.2@sha256:b1ad7e3c63f732a5f6daa466e8116be4f545b3b120383a64dcb62beb00a660cc
    labels:
      folder.view3: Tools
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/homebox.png
      traefik.enable: true
      traefik.docker.network: homelab_tools
      traefik.http.routers.homebox.rule: Host(`homebox.${SECRET_DOMAIN}`)
      traefik.http.routers.homebox.entryPoints: websecure
      traefik.http.services.homebox.loadbalancer.server.port: 7745
    volumes:
      - "${SECRET_APPDATA}/homebox:/data/"
    user: ${UID}:${GID}
    environment:
      TZ: ${TZ}
      HBOX_LOG_LEVEL: info
      HBOX_LOG_FORMAT: text
      HBOX_WEB_MAX_FILE_UPLOAD: 10
      HBOX_OPTIONS_ALLOW_ANALYTICS: false
      HBOX_OPTIONS_ALLOW_REGISTRATION: false
      HBOX_AUTH_API_KEY_PEPPER: ${HBOX_AUTH_API_KEY_PEPPER}
    networks:
      - tools
    restart: always
