services:
  matrix:
    container_name: matrix
    image: ghcr.io/element-hq/synapse:v1.162.0@sha256:6b84a7bbac36f080b2d2e51e0289cf1b08b349598ea44a558df38d558f2c2311
    labels:
      folder.view3: Tools
      net.unraid.docker.icon: file://${SECRET_APPDATA}/icons/matrix.png
      traefik.enable: true
      traefik.http.routers.matrix.rule: Host(`matrix.${SECRET_DOMAIN}`)
      traefik.http.routers.matrix.entryPoints: websecure
      traefik.http.services.matrix.loadbalancer.server.port: 8008
    volumes:
      - "${SECRET_APPDATA}/matrix:/data"
    environment:
      TZ: ${TZ}
      UID: ${UID}
      GID: ${GID}
      SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
    networks:
      - tools
    restart: always

  matrix-web:
    container_name: matrix-web
    image: ghcr.io/element-hq/element-web:v1.12.29@sha256:da32e88c8dafe2c3d4f40ca5e90ab2f43a7c9ac35f0977ec7662dcb4fdcd56d8
    labels:
      folder.view3: Tools
      net.unraid.docker.icon: file://${SECRET_APPDATA}/icons/matrix-web.png
      traefik.enable: true
      traefik.http.routers.matrix-web.rule: Host(`matrix-web.${SECRET_DOMAIN}`)
      traefik.http.routers.matrix-web.entryPoints: websecure
      traefik.http.services.matrix-web.loadbalancer.server.port: 80
    environment:
      TZ: ${TZ}
    networks:
      - tools
    restart: always
