services:
  matrix:
    container_name: matrix
    image: ghcr.io/element-hq/synapse:v1.157.0@sha256:53a686c52cdfca5fdb0adff5ef10b276b1d0971931b09815a9eb6b48d7188a1a
    labels:
      folder.view3: Tools
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/matrix.png
      traefik.enable: true
      traefik.http.routers.matrix.rule: Host(`matrix.${SECRET_DOMAIN}`)
      traefik.http.routers.matrix.entryPoints: websecure
      traefik.http.services.matrix.loadbalancer.server.port: 8008
    volumes:
      - "${SECRET_APPDATA}/matrix:/data"
    environment:
      TZ: ${TZ}
      UID: ${UID}
      GID: ${GID}
      SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
    networks:
      - tools
    restart: always

  matrix-web:
    container_name: matrix-web
    image: ghcr.io/element-hq/element-web:v1.12.23@sha256:2a65f32acc6fd7163523d1c4b5174de354b5ceb085898b15898f4d8ea01a8e3d
    labels:
      folder.view3: Tools
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/matrix-web.png
      traefik.enable: true
      traefik.http.routers.matrix-web.rule: Host(`matrix-web.${SECRET_DOMAIN}`)
      traefik.http.routers.matrix-web.entryPoints: websecure
      traefik.http.services.matrix-web.loadbalancer.server.port: 80
    environment:
      TZ: ${TZ}
    networks:
      - tools
    restart: always
