services:
  matrix:
    container_name: matrix
    image: ghcr.io/element-hq/synapse:v1.155.0@sha256:a87d002fba8efba807af19a876f488f4a9d298d6b62f5bab66d14e311a355e99
    labels:
      folder.view3: Tools
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/matrix.png
      traefik.enable: true
      traefik.http.routers.matrix.rule: Host(`matrix.${SECRET_DOMAIN}`)
      traefik.http.routers.matrix.entryPoints: websecure
      traefik.http.services.matrix.loadbalancer.server.port: 8008
    volumes:
      - "${SECRET_APPDATA}/matrix:/data"
    environment:
      TZ: ${TZ}
      UID: ${UID}
      GID: ${GID}
      SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
    networks:
      - tools
    restart: always

  matrix-web:
    container_name: matrix-web
    image: ghcr.io/element-hq/element-web:v1.12.22@sha256:c93f51c0445ce48be5c2d66a61470ba51a78315c7c60a4fc0e791595b96f3a96
    labels:
      folder.view3: Tools
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/matrix-web.png
      traefik.enable: true
      traefik.http.routers.matrix-web.rule: Host(`matrix-web.${SECRET_DOMAIN}`)
      traefik.http.routers.matrix-web.entryPoints: websecure
      traefik.http.services.matrix-web.loadbalancer.server.port: 80
    environment:
      TZ: ${TZ}
    networks:
      - tools
    restart: always
