services:
  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr:8.5.0@sha256:5da14297a11aa910582d800f0edcb8f9e9d488642083c01dc34950f6449d9214
    labels:
      folder.view2: Media
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/recyclarr.png
    volumes:
      - "${SECRET_APPDATA}/recyclarr:/config"
    user: ${UID}:${GID}
    environment:
      TZ: ${TZ}
      COMPlus_EnableDiagnostics: "0" # Fix the .Net CoreCLR crash on ReadOnly Filesystem
      CRON_SCHEDULE: "@daily"
      RADARR_API_KEY: ${SECRET_RADARR_API_KEY}
      SONARR_API_KEY: ${SECRET_SONARR_API_KEY}
    networks:
      - media-backend
    restart: always
    depends_on:
      radarr:
        condition: service_started
        restart: true
      sonarr:
        condition: service_started
        restart: true
