services:
  error-pages:
    image: ghcr.io/tarampampam/error-pages:3.8@sha256:b8ded6f847df91075429cf79cb9491bfd7d96de69936555498a2ff0614e003e4
    container_name: error-pages
    labels:
      folder.view3: Ingress
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/error-pages.png
      traefik.enable: true
      traefik.docker.network: homelab_webserver-internal
      traefik.http.routers.errorpages.rule: HostRegexp(`.+`)
      traefik.http.routers.errorpages.priority: 10
      traefik.http.routers.errorpages.entryPoints: websecure
      traefik.http.services.errorpages.loadbalancer.server.port: 8080
      traefik.http.routers.errorpages.middlewares: error-pages-middleware
      traefik.http.middlewares.error-pages-middleware.errors.service: errorpages
      traefik.http.middlewares.error-pages-middleware.errors.status: 400-599
      traefik.http.middlewares.error-pages-middleware.errors.query: /{status}.html
    environment:
      TZ: ${TZ}
      TEMPLATE_NAME: "shuffle"
      SHOW_DETAILS: "true"
    networks:
      - webserver-internal
    restart: always
