services:
  error-pages:
    image: ghcr.io/tarampampam/error-pages:4.2@sha256:6d42b5d6e1a014fa2373e3587f9e85c25589a089fd5f6fc4f2a496858f5e365d
    container_name: error-pages
    labels:
      folder.view3: Ingress
      net.unraid.docker.icon: file://${SECRET_APPDATA}/icons/error-pages.png
      traefik.enable: true
      traefik.docker.network: homelab_webserver-internal
      traefik.http.routers.errorpages.rule: HostRegexp(`.+`)
      traefik.http.routers.errorpages.priority: 10
      traefik.http.routers.errorpages.entryPoints: websecure
      traefik.http.services.errorpages.loadbalancer.server.port: 8080
      traefik.http.routers.errorpages.middlewares: error-pages-middleware
      traefik.http.middlewares.error-pages-middleware.errors.service: errorpages
      traefik.http.middlewares.error-pages-middleware.errors.status: 400-599
      traefik.http.middlewares.error-pages-middleware.errors.query: /{status}
    environment:
      TZ: ${TZ}
      TEMPLATE_NAME: "lost-in-space"
      SHOW_DETAILS: "true"
    networks:
      - webserver-internal
    restart: always
