services:
  hermes-w: &hermes_service
    container_name: hermes-w
    image: ghcr.io/zaggash/hermes-agent:v2026.7.20@sha256:9abd20e5a60bdc78f6077ede731d653569842f50bd802bfed3bb07d8c317c97f
    command: gateway run
    labels:
      folder.view3: Tools
      net.unraid.docker.icon: ${SECRET_APPDATA}/icons/hermes.png
    volumes:
      - "${SECRET_APPDATA}/hermes/w-agent:/opt/data/"
    environment:
      TZ: ${TZ}
      HERMES_UID: ${UID}
      HERMES_GID: ${GID}
    networks:
      - gluetun
    restart: always

  hermes-p:
    <<: *hermes_service
    container_name: hermes-p
    volumes:
      - "${SECRET_APPDATA}/hermes/p-agent:/opt/data/"
