services:
  hermes-w: &hermes_service
    container_name: hermes-w
    image: ghcr.io/zaggash/hermes-agent:v2026.7.30@sha256:a148c8bb30253306b08ae5d1be38782ca5736469a650fcf182738aa41aaddf02
    command: gateway run
    labels:
      folder.view3: Tools
      net.unraid.docker.icon: file://${SECRET_APPDATA}/icons/hermes.png
    volumes:
      - "${SECRET_APPDATA}/hermes/w-agent:/opt/data/"
    environment:
      TZ: ${TZ}
      HERMES_UID: ${UID}
      HERMES_GID: ${GID}
    networks:
      - gluetun
    restart: always

  hermes-p:
    <<: *hermes_service
    container_name: hermes-p
    volumes:
      - "${SECRET_APPDATA}/hermes/p-agent:/opt/data/"
