services:
  hermes-w: &hermes_service
    container_name: hermes-w
    image: ghcr.io/zaggash/hermes-agent:v2026.9.24@sha256:9fd2ac88b1dd7854e0fd34cb649a93c1dd21ce156029cb69ab95b1581399c235
    command: gateway run
    labels:
      folder.view3: Tools
      net.unraid.docker.icon: file://${SECRET_APPDATA}/icons/hermes.png
    volumes:
      - "${SECRET_APPDATA}/hermes/w-agent:/opt/data/"
    environment:
      TZ: ${TZ}
      HERMES_UID: ${UID}
      HERMES_GID: ${GID}
    networks:
      - gluetun
    restart: always

  hermes-p:
    <<: *hermes_service
    container_name: hermes-p
    volumes:
      - "${SECRET_APPDATA}/hermes/p-agent:/opt/data/"
